# Generated by Django 5.2.14 on 2026-05-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='resolution',
            field=models.TextField(default='Sem resolução'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
