# Generated by Django 5.2.14 on 2026-05-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_options_story_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='resolution',
        ),
    ]
